### ISSUE TITLE
update Infragram pics in store for red filters

### ISSUE THREAD

**Issue by jywarren** [publiclab/publiclab-kits#1]
before beginning to ship red filters

**Comment by jywarren** [comment]
@mathewlippincott are you confident in deprecating blue filters... any evidence that they work better with _some_ cameras? @Nataliegurl says 2-3 wk timeline (~1st week of Aug) for updating the docs and shipping new filters. 
- [x] web instructions/wikis
- [ ] online store photos/text
- [x] print instructions

Do we want to change the color of the blue ink on the envelope?

**Comment by jywarren** [comment]
print instructions look good - they don't mention filter color. If we ever ship BOTH in the same pack, we should probably have a "RED OR BLUE" insert card. It could say:

**Should you use a RED or BLUE filter?**

Early research by Public Lab contributors led to a blue filter technique for making Infragram cameras. But recent research on PublicLab.org has shown that red filters work better -- and on a wider range of cameras. Blue filters did not work on most CMOS cameras, especially cheaper webcams. We now use Rosco #17 "Fire" filters.

**Comment by Nataliegurl** [comment]
Cool, In that case, I think we will just have Eberhardt assemble packs with
blues until the one runs out, then we will sub in the red. Does that work?
Sound fair?

**Comment by jywarren** [comment]
I just updated the Infragram wiki page to talk about red vs. blue filters. Yes, that works. Do you want to re-print the envelopes with red ink instead of blue at some point? Are we shipping red white balance cards? Can we source a white balance card that won't fade in the sun?

**Comment by jywarren** [comment]
I'll need to take some photos of red filter material, and could you take some nice ones of the filter pack opened with the parts displayed, or mail me some so I can do a photoshoot? Also, so we're just skipping the "RED OR BLUE" card in favor of doing a clean switch once blues run out?

**Comment by Nataliegurl** [comment]
I don't know what to look for when it comes to "red white balance cards".
We could reprint the envelopes with red ink, but I don't think it is very
important. We are still shipping the other blue filter, so a RED OR BLUE
card might be helpful still. It is just the one that is being discontinued.
The Blue 2007. The Blue will continue to be shipped with the Red 19.

So just to be clear, what do you want pictures of? An opened filter pack
with which parts displayed? Red and blue? Blue and Blue (as is currently)?
Or email you a current filter pack?

FYI we do not have any red filters here yet? I will need to order some for
Eberhardt when Blue 2007 runs low. I borrowed a little piece from a Mobius
sample we had, when I was messing with the Spec-Infragram cam researching.

**Comment by jywarren** [comment]
You can read about the white balance cards we use here: http://publiclab.org/notes/cfastie/07-17-2013/balancing-act

A card the color of the filter is required, but the blue ones fade badly in the sun and we always meant to replace them but never had time to do so. This is a good opportunity to get it right! 

Chris Fastie wrote about the fading issue here: http://publiclab.org/notes/cfastie/09-11-2013/fade-out

The chroma key paper we used won't hold it's color. @mathewlippincott - do you have any ideas on colorfast red paper? 

Re: photos, we need to replace the photos in the store showing blue filters: http://store.publiclab.org/products/infragram-diy-filter-pack

<img width="400" src="https://cloud.githubusercontent.com/assets/24359/3707904/72906fc6-143b-11e4-844b-d6a2a4a3b61a.png"/>
![image](https://cloud.githubusercontent.com/assets/24359/3707908/7df510a6-143b-11e4-82d9-167b90389e11.png) <img width="200" src="https://cloud.githubusercontent.com/assets/24359/3707917/92746d74-143b-11e4-9c82-d93dea744d25.png" />

**Comment by jywarren** [comment]
However i'd like to get a better image than the first one. I'm happy to do a photo shoot but would need a red filter pack to do so... or I could try to fake it with Photoshop :-P

**Comment by Nataliegurl** [comment]
LOL! That might be the easiest option! I guess I'll order some red filters
so we can get started on this. I'll just have them sent here so we have
some to play with and take the rest over to Eberhardt.

**Comment by jywarren** [comment]
changing name since all that's left is the store pics. Removed "docs, print & web, for red/blue filter options"

**Comment by Nataliegurl** [comment]
Hi Jeff,

We got the red filter samples and I put some in the mail for you Friday. I
don't know if they went out though but they should leave today hopefully.

Natalie Mayorga

Kits Initiative Manager
Public Lab
412 NW Couch, Ste. 401
Portland, OR 97209
T: 504.239.4642
F: 504.324.0401
Natalie@publiclab.org
www.publiclab.org

FB: www.facebook.com/PublicLab
Twitter: @PublicLab, @natcat5050
Instagram: public_lab

**Comment by Nataliegurl** [comment]
@jywarren did you ever receive these? We are ordering the red paper today or picking it up.

**Comment by jywarren** [comment]
Did u want me to test them on sanm cams? What tests should j do?

**Comment by Nataliegurl** [comment]
No, I think just set up a photo shoot, with some options for the store and the wiki. An updated kit.

**Comment by jywarren** [comment]
https://www.dropbox.com/sh/li0222qjerhd9f5/AAATXQYrqyiUXeGh8Qg3xEgwa?dl=0

or /plots/retail/infragram/red-filters/

Looking good!
