### ISSUE TITLE
upsell lists collimation slits for infragram webcam

### ISSUE THREAD

**Issue by jywarren** [publiclab/publiclab-kits#12]
and possibly other products?
- which products is it shown for?
- are people buying them thinking they'll get better accuracy in their infragram webcams?
- let's adjust this to show only for spectrometry related goods.

**Comment by Nataliegurl** [comment]
It just  upsells for all spectrometer adds to their cart. So bundles, smart
spec, DSK, and foldups.

Natalie Mayorga

Kits Initiative Manager
Public Lab
412 NW Couch, Ste. 401
Portland, OR 97209
T: 504.239.4642
F: 504.324.0401
Natalie@publiclab.org
www.publiclab.org

FB: www.facebook.com/PublicLab
Twitter: @PublicLab, @natcat5050
Instagram: public_lab

**Comment by jywarren** [comment]
Great, so we're good on this? Closing.
