### ISSUE TITLE
WheeStat/Smoky Mot. Scientific Incubation co branding

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/publiclab-kits#15]
![smokymtsci](https://cloud.githubusercontent.com/assets/7808557/4064529/5aaf3d7e-2e12-11e4-9d65-69196c4794ad.png)

@jywarren @mathewlippincott

**Comment by jywarren** [comment]
What about something like this, where we work the above design into the "circuitboard" ? I ask because our typical box style so far is pretty specific. 

![wheestat](https://cloud.githubusercontent.com/assets/24359/4084078/f8fa1a70-2f03-11e4-9659-2aa3805723ac.png)

**Comment by mathewlippincott** [comment]
that's a nice start to some branding. @wheesci any thoughts?

just for completeness, here was the quick logo draft I sent over earlier
![screen shot 2014-08-27 at 11 22 31 am](https://cloud.githubusercontent.com/assets/1203280/4095010/b68e0010-2fae-11e4-9720-5ec68e8a202a.png)

**Comment by jywarren** [comment]
I like mathew's design - was thinking though that we may be mixing the branding of the organization with the branding of the product, which is why i didn't riff directly on it for the sketch I did. I thought maybe we could place the SMS logo below, next to Public Lab or something... not really sure. Or maybe it's fine to brand the kit with SMS, as long as we make clear the relationship with PL?

**Comment by Nataliegurl** [comment]
I sort of feel like the SMS logo should be below somewhere. For our
purposes we need consistency in design, so something like Jeff's logo for
the kit, and Mathew's SMS logo for the company. Like "brought to you by..
(SMS)"

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by mathewlippincott** [comment]
we need some sort of standard "boots logo hugging another logo" to indicate incubation.
![screen shot 2014-08-29 at 4 54 23 pm](https://cloud.githubusercontent.com/assets/1203280/4097513/d3f8eb64-2fd7-11e4-993f-448c07aadc01.png)

**Comment by Nataliegurl** [comment]
+1

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

On Fri, Aug 29, 2014 at 4:54 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
Hi, all - still need text, but here's the overall (PDF is in dropbox):

![screen shot 2014-09-04 at 11 51 01 am](https://cloud.githubusercontent.com/assets/24359/4152059/556f13fe-344b-11e4-8282-23306f2a8a28.png)

**Comment by Nataliegurl** [comment]
How about

"WheeStat
A DIY potentiostat for trace detecting metal ions in water, including lead,
arsenic and mercury."

Is that too long?

## 

Natalie Mayorga

_Kits Initiative Manager Public Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874 <503.902.5874>_

*F: 504.324.0401 <504.324.0401> *

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_
- FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab*

_Twitter: @PublicLab, @natcat5050 *
*Instagram: public_lab_

**Comment by WheeSci** [comment]
Looks good to me (assuming that the text is appropriate).  How about “DIY electrochemical analysis for education and environmental monitoring”?
Jack

**Comment by jywarren** [comment]
It'd be great to be specific: lead, arsenic and mercury

if that's correct, I'd like to go with that --

"A DIY potentiostat for detecting lead,
arsenic and mercury in water."

I think we could make that fit.

And is there a list of parts I could paraphrase for the "parts list"?

**Comment by Nataliegurl** [comment]
While you can measure these ions using this potentiostat, measuring them at very low concentrations requires addition of acid and the use of more expensive electrodes than the ones we provide with the kit.  Proving that you have what you think you have also requires that you have standard samples of the metals.  So, yes, you can measure Hg, As and Pb with the wheestat, just not right out of the box.
"WheeStat
For DIY analysis of metal ions (Hg, As, Pb, etc) in water."

---

Jack

**Comment by WheeSci** [comment]
Parts list (copied from: http://publiclab.org/notes/JSummers/08-07-2014/wheestat-kit-assembly#What+is+in+the+kit?):  (1) a vhs tape box which is used for an enclosure. (2) A Tiva LaunchPad development board (the red circuit board). (3) An analog circuit board (green board). (4) Three alligator clips. (5) A micro usb cable (6) A three conductor cable. (7) Two headers for connecting the boards (blue things in the lower left corner), (8) Stuff for making a silver / silver chloride reference electrode, (9) two graphite rods and electrical tape for working and auxiliary electrodes, and (10) a 1 GB usb flash drive with the most up to date code (as of when your kit was shipped from NC).

**Comment by jywarren** [comment]
How about "For DIY analysis of trace metals in water." ?

**Comment by jywarren** [comment]
Then, below:
- Online documentation & user forums
- Detect metal ions: Hg, As, Pb
- Open-source analysis software

What can you detect without the extra electrodes?

**Comment by jywarren** [comment]
![screen shot 2014-09-04 at 1 54 48 pm](https://cloud.githubusercontent.com/assets/24359/4153854/f251eb22-345c-11e4-9fb5-65cd1d0af8a3.png)

**Comment by WheeSci** [comment]
Looks good!
Jack

**Comment by WheeSci** [comment]
You can probably detect the same stuff, but you can not go acidic and that will limit the concentration range that you can measure.
Jack

**Comment by jywarren** [comment]
Oh, also i'm sorry i'm in such a rush today but I couldn't find the Smokey Mountain logo Mathew did in vector -- the version in there is raster and needs to be swapped!

And I haven't had a moment to make outlines for everything. I hope that's OK with Charles, but can try to re-do it -- there was that weird thing about making outlines of a dotted line which I had to look up before I could figure it out in Illustrator... very weird.

**Comment by mathewlippincott** [comment]
its in plots/retail/incubation/smokymountainscientific

**Comment by mathewlippincott** [comment]
looking good!
