### ISSUE TITLE
create web/print/SDcard instructions for Infragram P&S

### ISSUE THREAD

**Issue by jywarren** [publiclab/publiclab-kits#2]
SD card files being prepared here: https://github.com/publiclab/infragram-ps

**Comment by Nataliegurl** [comment]
How close are these to completion?

**Comment by jywarren** [comment]
I will spend some time tomorrow morning but what's the due date? We had
wanted to do some animated gifts to show the blinking colors and sequence
but maybe I can do it as some flat graphics instead.

How close are these to completion?

**Comment by Nataliegurl** [comment]
No particular due date, but if the point and shoots are shipping this week or next, we are going to want to get the SD cards pretty darn quick. I would say Tuesday at the latest?

**Comment by jywarren** [comment]
OK, but we also need to know if users will have to upgrade firmware themselves or if it'll be upgraded already. The answer from the factory was unclear. This will affect the instructions, but could be a last-minute tweak.

**Comment by Nataliegurl** [comment]
Jason is ready to ship initial 100 units. What specifically do I need to ask about firmware?

**Comment by jywarren** [comment]
OK, these are almost done now, take a look: http://publiclab.org/wiki/infragram-point-shoot

I also made a PDF and included it in the repository: https://github.com/publiclab/infragram-ps

https://github.com/publiclab/infragram-ps/blob/master/README.pdf?raw=true

**Comment by jywarren** [comment]
Whether it is v1.20 and if they can set it to that for us, or if we have to
do it ourselves.

**Comment by jywarren** [comment]
Also, i think the actual instructions insert should have more information on how/why this technique works, or at least a reference to that research. I'll add something to the intro paragraph, or excerpt from the main Infragram wiki page.

**Comment by Nataliegurl** [comment]
Awesome,

Thank you Jeffrey. This is finally taking shape and we are getting ready to
ship finally.

**Comment by jywarren** [comment]
Added more info on the technique in general, updated PDF as well, other small tweaks. Just need to know about firmware now.

**Comment by Nataliegurl** [comment]
Asking now

**Comment by mathewlippincott** [comment]
We can load the firmware into the root directory no matter what, and I
think we should do the upgrade before shipping if need be.

On Fri, Jul 18, 2014 at 9:51 AM, Natalie notifications@github.com wrote:

> Asking now
> 
> Natalie Mayorga
> 
> Kits Initiative Manager
> Public Lab
> 412 NW Couch, Ste. 401
> Portland, OR 97209
> T: 504.239.4642
> F: 504.324.0401
> Natalie@publiclab.org
> www.publiclab.org
> 
> FB: www.facebook.com/PublicLab
> Twitter: @PublicLab, @natcat5050
> Instagram: public_lab
> 
> On Fri, Jul 18, 2014 at 9:47 AM, Jeffrey Warren notifications@github.com
> 
> wrote:
> 
> > Added more info on the technique in general, updated PDF as well, other
> > small tweaks. Just need to know about firmware now.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/publiclab/publiclab-kits/issues/2#issuecomment-49453273>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/publiclab/publiclab-kits/issues/2#issuecomment-49453583
> .

## 

Mathew Lippincott
publiclaboratory.org
503 852 1669

**Comment by jywarren** [comment]
OK, so shall I change the on-SD card text from:

> Some cameras may require a firmware upgrade to v1.20. If you've gotten your Infragram Point & Shoot from Public Lab's Kits initiative (through Kickstarter or the Public Lab store), both the config file and the v1.20 firmware should be on the SD card provided (in addition to this documentation!). However, you'll still have to load up the white balance file as described in "Installing config file" below.

to:

> Some cameras may require a firmware upgrade to v1.20. If you've gotten your Infragram Point & Shoot from Public Lab's Kits initiative (through Kickstarter or the Public Lab store), the v1.20 firmware should already be installed, but will also ship on the SD card (in addition to this documentation!) in case it's needed. However, you'll still have to load up the white balance file as described in "Installing config file" below. 

Sound good?

**Comment by Nataliegurl** [comment]
So is this the pdf for the instructions booklet? https://github.com/publiclab/infragram-ps/blob/master/README.pdf?raw=true
Is it ready to go like this? Should I send to the printer or do we want it formatted into a trifold? 6 pages or 3 back to back rather...

**Comment by jywarren** [comment]
We could print it, but i hadn't thought of that. Mathew's insert card says
to go to the website -- i guess it should specifically point to the
/wiki/infragram-point-shoot page. But if we include the PDF it won't matter
as much. What do you think?

**Comment by Nataliegurl** [comment]
Yeah, where is the insert card, and who is printing then? I think it should specifically point to the point and shoot page if we are not going to print instructions.

**Comment by jywarren** [comment]
I just saw what mathew put together, it looks great, and it's in the same
repository (that goes on the SD card) as the PDF.

**Comment by Nataliegurl** [comment]
@mathewlippincott  It does look good. Is it enough or should it also have /wiki/infragram-point-shoot ?
I can send to Eberhardt for a quote today if it's ready.

**Comment by mathewlippincott** [comment]
Can we make a "Getting Started" HTML page that is in the home directory of the camera and that links straight to the wiki page? Then we print the minimal PDF I created, with the caveat "go to webpage or click 'Getting Started' on the camera's home directory."  Then we're done for now, and while we now require the internet to view the instructions, we've future-proofed our SD card.

**Comment by jywarren** [comment]
We could add a section to the top of the PDF that says "A newer version of
these instructions may be found at
http://publiclab.org/wiki/infragram-point-shoot"

in a yellow box -- how does that sound? Does the PDF provide enough of a
"getting started" for folks who don't have a net connection?

On Tue, Jul 22, 2014 at 3:22 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
I asked the infrared and organizers mailing lists for final input.

**Comment by Nataliegurl** [comment]
Great! Let me know when we have the final version, and I will send to our
card duplicator. This weekend or Monday if possible.

Natalie Mayorga

Kits Initiative Manager
Public Lab
412 NW Couch, Ste. 401
Portland, OR 97209
T: 504.239.4642
F: 504.324.0401
Natalie@publiclab.org
www.publiclab.org

FB: www.facebook.com/PublicLab
Twitter: @PublicLab, @natcat5050
Instagram: public_lab
