### ISSUE TITLE
unified box design

### ISSUE THREAD

**Issue by jywarren** [publiclab/publiclab-kits#5]
@nataliegurl is sourcing the box, @jywarren is doing the sticker design (http://publiclab.org/wiki/kit-packaging).
@mathewlippincott is sourcing the vector file for the print artwork

**Comment by Nataliegurl** [comment]
We have the stickers for the point and shoot in PDX office & ready to go. We need updated stickers for the rest of the kits @jywarren

**Comment by jywarren** [comment]
These are the front stickers, right? Did you see the draft design i'd posted above? Any feedback, further information that's got to be on it?

**Comment by Nataliegurl** [comment]
Should we put the contents on there somewhere? How about camera located in the conduit box or something to that effect. So customers know to look there first before saying its missing. Trying to address that issue as well.

**Comment by jywarren** [comment]
I think if possible we should keep the front focused and clean. If we could put that in the instructions (like in the current DSK instructions where we list the parts) that's be great. Contents on the outside of the box would be nice... let me try.

**Comment by jywarren** [comment]
Something a bit more like this, but with a better image depicting scanning something. I'm not sold on the font as it's not readable at small sizes but am trying for something that'd be a bit more eye-catching. Could try it on brown paper too... although can we print brown paper stickers? Maybe stick to white paper. 

[first draft](https://cloud.githubusercontent.com/assets/24359/3630305/fcf8cd30-0ea9-11e4-9d92-71e9a6627bb2.png)

**Comment by Nataliegurl** [comment]
I like it. Better picture would be nice.

**Comment by jywarren** [comment]
![screen shot 2014-07-25 at 11 24 28 am](https://cloud.githubusercontent.com/assets/24359/3705001/10387768-141a-11e4-83ac-89da9f288c9d.png)

Almost done. I'm going to try other colors and shapes besides circles, for other kits we have.

**Comment by jywarren** [comment]
Infragram options:

![screen shot 2014-07-25 at 1 10 11 pm](https://cloud.githubusercontent.com/assets/24359/3705405/960b36e2-141e-11e4-81bc-65256bd17f82.png)

**Comment by Nataliegurl** [comment]
Nice! These are all beautiful!

Have you been able to send the email re: the P&S insert, I would like to
have those ordered today.

Also, if you can, Shannon has solicited input re: the information being
printed on the unified box.

Thanks for your work on this!

**Comment by jywarren** [comment]
I can do that today, sorry am having a crazy overloaded day :-(

Yes, i'm going to do an edit of the box itself, partially so it says something under the sticker, for non-specific shipping. Will hopefully get that by today but will focus on getting the P+S thing done first, and fixing images on the PL wiki :-(

**Comment by jywarren** [comment]
Do you like/dislike the wavy lines? @sdosemagen any opinions on those?

OK, box itself, tweaked for consistency with the stickers: 

![screen shot 2014-07-25 at 2 16 28 pm](https://cloud.githubusercontent.com/assets/24359/3706299/fdd47cb2-1427-11e4-906b-97214472870e.png)

**Comment by Nataliegurl** [comment]
Wait a minute, the top and bottom of the box should be blank right? Top for
the individual labels and bottom for postage.

**Comment by jywarren** [comment]
Yes but why not put something under the sticker in case we want to ship
without -- something generic.

**Comment by Nataliegurl** [comment]
Cost. But maybe it's not significant.

**Comment by Nataliegurl** [comment]
After checking, the cost is not significant, so if we want to print on top
that should be fine.

**Comment by jywarren** [comment]
great, that'll be good for new kits, or for kits we don't have labels for yet, and such. Or for shipments of combined crap.

**Comment by jywarren** [comment]
I'm wondering about the stickers -- is it possible to get matte stickers, or to get slightly nicer paper and get it adhesive backed, or what are our options? Slightly nicer paper (linen or with faint texture) would make these look super awesome. I just don't know what sticker technology can do.

**Comment by jywarren** [comment]
I guess i think this is a question for Charles at Eberhardt.

**Comment by Nataliegurl** [comment]
agree

**Comment by Nataliegurl** [comment]
Ok is this good to go then? Can you send me a vector format for this box
design Jeff? or .ai?

We are running low on boxes here and I need to place this order if we are
ready.

**Comment by Nataliegurl** [comment]
Never mind. I think I found it here:
http://publiclab.org/wiki/infragram-point-shoot

Is it ready to go is my last question?

**Comment by jywarren** [comment]
I edited the version in Dropbox.
https://www.dropbox.com/work/plots/retail/universal-boxes

And if you send them this link they can get the fonts:
https://www.theleagueofmoveabletype.com/junction

What did you find on that wiki page? The insert?

**Comment by Nataliegurl** [comment]
No that was the wrong link, sorry. I found the dropbox file.
What I meant to paste:
/Dropbox (Public Lab)/plots/retail/universal-boxes

Will do. Sending to the box manufacturer today to get these ordered.

**Comment by jywarren** [comment]
super. we get one more look at the proof, right?

**Comment by Nataliegurl** [comment]
Should. I am asking about that right now. Ordering 1,500 for our first run
and we need them delivered I think. Total cost for initial run $1,854.00

**Comment by mathewlippincott** [comment]
@Nataliegurl's timeline:
We are going to need these fairly quickly, as our boxes should be prepared and delivered sometime next week, and we are currently out of Desktop Spectrometry Boxes. We need labels promptly, so just circling back to this,

-Jeff are you ready to make a decision on the sticker paper we are going to use?
-Mathew have you considered which will be best?
-Noah are we going to be able to store the new boxes and integrate sticker label application into production, smoothly?
-Charles would you like us place the order and have the sticker delivered to you for cutting and printing? Keep in mind, there will be several different labels to print, but all will be cut to the same dimensions.

Thanks for your attention to this folks, unfortunately the time is upon us, as we are running out of current boxes and the new ones will be on the way shortly.

**Comment by mathewlippincott** [comment]
I think jeff's choice of paper is nice aesthetically but the choice is really noah's for this first batch-- these stickers are going to require squeegie-ing and wetting to stick, and we should test something before we print a ton.

I'm not willing to jump into that production headache and commit to it.  we should print adhesive-backed stickers in a smaller run since we need them faster.

**Comment by Nataliegurl** [comment]
+1

**Comment by jywarren** [comment]
We're waiting for a response from charles about the paper he suggested --
I'd asked him how these would be attached and if there are other options.
Natalie, can you ping him?

**Comment by jywarren** [comment]
Ah I see you did, but can you ask him for suggestions on easy to apply
stickers?

**Comment by mathewlippincott** [comment]
Lets ask Charles for two things-- to source peel and stick stickers and 2) to get samples of the "wine bottle" labels for us to test.

**Comment by mathewlippincott** [comment]
Updated 3" box in dropbox plots/retail/universal-boxes/universalbox_3in.ai
version with outlined text there also

**Comment by Nataliegurl** [comment]
Cool! On it.

**Comment by jywarren** [comment]
> Natalie: Jeff & Mathew -In the meantime, can we work on finalizing the design files for each kit and forward them to Eberhardt? They look pretty good as they are, but are they ready to go do you feel, and are all the kits we currently retail represented?

Which kits do we need designs for? I thought the first one we're doing is just the Desktop kit, and presumably the Smartphone kit too, since it uses the same box. What others are we transitioning now -- can you send a list? Thanks!

**Comment by mathewlippincott** [comment]
I think we're keeping the infragram cameras in envelopes-- correct?

**Comment by Nataliegurl** [comment]
I think:

-DSK
-SmartSpec - I don't know if we just want to keep this the same and just
slap Smartphone stickers on it but I think its a good opportunity to set it
apart.
-P&S
-Oil Kit
-Fido
-coming soon WheeStat
- thermal flashlight?

That's probably it for now unless I'm missing something.

**Comment by jywarren** [comment]
OK, these are coming together. I think we have finals for dsk, smartphone, infragram webcam, and I'm still tweaking infragram PS, but it's close. 

do we have strong opinions about infragram theme color being red instead of blue now? These are setup so that infragrams are blue, as traditionally they are. But we could swap with the red from the spectrometer version. 

fido, still waiting on some sample imagery and text. oil kit we're not there yet, so is there anything else urgently needing a new sticker? Do we want to get prepped for a rebrand of the flat envelopes too?

**Comment by jywarren** [comment]
oh btw https://www.dropbox.com/sh/g4alfisqnqi0qz0/AADxCgcd3kTcYpZ5n4MSeLTCa

**Comment by jywarren** [comment]
So glad btw that our design inadvertently resembles this:
![6a00d83451b54669e2017ee6a97317970d](https://cloud.githubusercontent.com/assets/24359/4001636/2f57067c-2965-11e4-84f0-407528f2154b.jpg)
